version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: WEATHER_FORCAST_2024
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    networks:
      - weather-network

  api:
    image: weather
    build: 
      context: server
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    networks:
      - weather-network
    ports:
      - "5000:5000"

  ui:
    image: ui
    build:
      context: frontend
      dockerfile: ./Dockerfile
    depends_on:
      - api
    networks:
      - weather-network
    ports:
      - "3000:3000"

networks:
  weather-network:
    driver: bridge

volumes:
  mongo_volume:
